import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { GlobalProgress, ProgressLink } from "./global-progress";
import Nav from "./nav";
import NavFramerMotion from "./nav-framer-motion";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Nav /> */}

        {/* <nav className="m-4 flex gap-4">
          <ProgressLink href="/">Home</ProgressLink>
          <ProgressLink href="/post/1">Post 1</ProgressLink>
          <ProgressLink href="/post/2">Post 2</ProgressLink>
          <ProgressLink href="/post/3">Post 3</ProgressLink>
        </nav> */}

        {children}
      </body>
    </html>
  );
}
